pub struct RunnerConfig {
    pub analysis_spec_path: String,
    pub cdm_database_schema: String,
    pub work_database_schema: String,
    pub output_path: String,
    pub database_name: String,
    pub pgwire_port: u16,
    pub pgwire_password: String,
    pub cohort_table_name: String,
    pub min_cell_count: u32,
}

pub fn generate_strategus_runner(cfg: &RunnerConfig) -> String {
    format!(
        r#"# Auto-generated by hades.trex — do not edit
Sys.setenv("_JAVA_OPTIONS" = "-Xmx4g")
Sys.setenv("VROOM_THREADS" = 1)

cdmDatabaseSchema <- "{cdm_schema}"
workDatabaseSchema <- "{work_schema}"
outputLocation <- "{output_path}"
databaseName <- "{db_name}"
minCellCount <- {min_cell_count}
cohortTableName <- "{cohort_table}"

connectionDetails <- DatabaseConnector::createConnectionDetails(
  dbms = "postgresql",
  server = "localhost/trex",
  port = {port},
  user = "trex",
  password = "{password}"
)

analysisSpecifications <- ParallelLogger::loadSettingsFromJson(
  fileName = "{spec_path}"
)

executionSettings <- Strategus::createCdmExecutionSettings(
  workDatabaseSchema = workDatabaseSchema,
  cdmDatabaseSchema = cdmDatabaseSchema,
  cohortTableNames = CohortGenerator::getCohortTableNames(cohortTable = cohortTableName),
  workFolder = file.path(outputLocation, databaseName, "strategusWork"),
  resultsFolder = file.path(outputLocation, databaseName, "strategusOutput"),
  minCellCount = minCellCount
)

if (!dir.exists(file.path(outputLocation, databaseName))) {{
  dir.create(file.path(outputLocation, databaseName), recursive = TRUE)
}}

ParallelLogger::saveSettingsToJson(
  object = executionSettings,
  fileName = file.path(outputLocation, databaseName, "executionSettings.json")
)

Strategus::execute(
  analysisSpecifications = analysisSpecifications,
  executionSettings = executionSettings,
  connectionDetails = connectionDetails
)
"#,
        cdm_schema = cfg.cdm_database_schema,
        work_schema = cfg.work_database_schema,
        output_path = cfg.output_path,
        db_name = cfg.database_name,
        min_cell_count = cfg.min_cell_count,
        cohort_table = cfg.cohort_table_name,
        port = cfg.pgwire_port,
        password = cfg.pgwire_password,
        spec_path = cfg.analysis_spec_path,
    )
}

pub fn generate_renv_restore_script(lockfile_path: &str, lib_path: &str) -> String {
    format!(
        r#"# Auto-generated by hades.trex — do not edit
if (!requireNamespace("renv", quietly = TRUE)) {{
  install.packages("renv", repos = "https://cloud.r-project.org")
}}

dir.create("{lib_path}", recursive = TRUE, showWarnings = FALSE)

renv::restore(
  lockfile = "{lockfile_path}",
  library = "{lib_path}",
  prompt = FALSE,
  clean = FALSE
)

cat("HADES_ENV_SETUP_COMPLETE\n")
"#,
        lockfile_path = lockfile_path,
        lib_path = lib_path,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generates_valid_r_script() {
        let script = generate_strategus_runner(&RunnerConfig {
            analysis_spec_path: "/studies/spec.json".to_string(),
            cdm_database_schema: "cdm_v5".to_string(),
            work_database_schema: "work".to_string(),
            output_path: "/results/output".to_string(),
            database_name: "site_a".to_string(),
            pgwire_port: 5433,
            pgwire_password: "secret".to_string(),
            cohort_table_name: "hades_cohort".to_string(),
            min_cell_count: 5,
        });
        assert!(script.contains("dbms = \"postgresql\""));
        assert!(script.contains("port = 5433"));
        assert!(script.contains("password = \"secret\""));
        assert!(script.contains("cdmDatabaseSchema <- \"cdm_v5\""));
        assert!(script.contains("workDatabaseSchema <- \"work\""));
        assert!(script.contains("databaseName <- \"site_a\""));
        assert!(script.contains("Strategus::execute"));
        assert!(script.contains("/studies/spec.json"));
    }

    #[test]
    fn escapes_backslashes_in_paths() {
        let script = generate_strategus_runner(&RunnerConfig {
            analysis_spec_path: "/path/with spaces/spec.json".to_string(),
            cdm_database_schema: "cdm".to_string(),
            work_database_schema: "work".to_string(),
            output_path: "/results".to_string(),
            database_name: "db".to_string(),
            pgwire_port: 5433,
            pgwire_password: "pass".to_string(),
            cohort_table_name: "hades_cohort".to_string(),
            min_cell_count: 5,
        });
        assert!(script.contains("/path/with spaces/spec.json"));
    }

    #[test]
    fn generates_setup_script() {
        let script = generate_renv_restore_script(
            "/studies/my-study/renv.lock",
            "/envs/my-study-lib",
        );
        assert!(script.contains("renv::restore"));
        assert!(script.contains("/studies/my-study/renv.lock"));
        assert!(script.contains("/envs/my-study-lib"));
    }
}
