[package]
name = "webapi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
lto = true
strip = true

[[example]]
name = "webapi"
path = "src/wasm_lib.rs"
crate-type = ["staticlib"]

[dependencies]
duckdb = { git = "https://github.com/p-hoffmann/trexsql-rs", rev = "9d6d6fb", features = ["vtab-loadable", "vscalar", "vtab-arrow"] }
duckdb-loadable-macros = { git = "https://github.com/p-hoffmann/trexsql-rs", rev = "9d6d6fb" }
libduckdb-sys = { git = "https://github.com/p-hoffmann/trexsql-rs", rev = "9d6d6fb", features = ["loadable-extension"] }
