use crate::error::{TransformationError, TransformationResult};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::fs;
use std::path::Path;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TransformationConfig {
    pub data_types: DataTypeConfig,
    pub functions: FunctionConfig,
    pub schema_handling: SchemaConfig,
    pub optimization: OptimizationConfig,
    pub formatting: FormattingConfig,
    pub rules: RulesConfig,
}

impl Default for TransformationConfig {
    fn default() -> Self {
        Self {
            data_types: DataTypeConfig::default(),
            functions: FunctionConfig::default(),
            schema_handling: SchemaConfig::default(),
            optimization: OptimizationConfig::default(),
            formatting: FormattingConfig::default(),
            rules: RulesConfig::default(),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DataTypeConfig {
    pub preserve_precision: bool,
    pub custom_mappings: HashMap<String, String>,
    pub handle_arrays: ArrayHandlingStrategy,
}

impl Default for DataTypeConfig {
    fn default() -> Self {
        Self {
            preserve_precision: true,
            custom_mappings: HashMap::new(),
            handle_arrays: ArrayHandlingStrategy::AsJson,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum ArrayHandlingStrategy {
    AsJson,
    AsDelimitedString,
    AsMultipleColumns,
    Error,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FunctionConfig {
    pub preserve_case: bool,
    pub enable_custom_functions: bool,
    pub custom_mappings: HashMap<String, String>,
}

impl Default for FunctionConfig {
    fn default() -> Self {
        Self {
            preserve_case: false,
            enable_custom_functions: true,
            custom_mappings: HashMap::new(),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SchemaConfig {
    pub default_schema: String,
    pub preserve_schema_names: bool,
    pub schema_mappings: HashMap<String, String>,
}

impl Default for SchemaConfig {
    fn default() -> Self {
        Self {
            default_schema: "PUBLIC".to_string(),
            preserve_schema_names: true,
            schema_mappings: HashMap::new(),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OptimizationConfig {
    pub use_column_store_hints: bool,
    pub enable_parallel_execution: bool,
    pub suggest_indexes: bool,
}

impl Default for OptimizationConfig {
    fn default() -> Self {
        Self {
            use_column_store_hints: true,
            enable_parallel_execution: true,
            suggest_indexes: false,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FormattingConfig {
    pub indent_size: usize,
    pub max_line_length: usize,
    pub capitalize_keywords: bool,
    pub preserve_comments: bool,
}

impl Default for FormattingConfig {
    fn default() -> Self {
        Self {
            indent_size: 2,
            max_line_length: 120,
            capitalize_keywords: true,
            preserve_comments: true,
        }
    }
}

impl TransformationConfig {
    pub fn to_file(&self, path: &std::path::Path) -> anyhow::Result<()> {
        let content = toml::to_string_pretty(self)?;
        std::fs::write(path, content)?;
        Ok(())
    }

    pub fn get_default_data_type_mappings() -> HashMap<String, String> {
        let mut mappings = HashMap::new();

        mappings.insert(
            "SERIAL".to_string(),
            "INTEGER GENERATED BY DEFAULT AS IDENTITY".to_string(),
        );
        mappings.insert(
            "BIGSERIAL".to_string(),
            "BIGINT GENERATED BY DEFAULT AS IDENTITY".to_string(),
        );
        mappings.insert("TEXT".to_string(), "NCLOB".to_string());
        mappings.insert("VARCHAR".to_string(), "NVARCHAR".to_string());
        mappings.insert("CHAR".to_string(), "NCHAR".to_string());
        mappings.insert("TIMESTAMPTZ".to_string(), "TIMESTAMP".to_string());
        mappings.insert("JSON".to_string(), "NCLOB".to_string());
        mappings.insert("JSONB".to_string(), "NCLOB".to_string());
        mappings.insert("UUID".to_string(), "NVARCHAR(36)".to_string());
        mappings.insert("INET".to_string(), "NVARCHAR(45)".to_string());
        mappings.insert("MACADDR".to_string(), "NVARCHAR(17)".to_string());

        mappings
    }

    pub fn get_default_function_mappings() -> HashMap<String, String> {
        let mut mappings = HashMap::new();

        mappings.insert("RANDOM".to_string(), "RAND".to_string());
        // NOW() is supported natively in HANA, no transformation needed
        mappings.insert(
            "CURRENT_TIMESTAMP()".to_string(),
            "CURRENT_TIMESTAMP".to_string(),
        );

        mappings
    }
}

impl TransformationConfig {
    pub fn from_file<P: AsRef<Path>>(path: P) -> TransformationResult<Self> {
        let content = fs::read_to_string(path).map_err(|e| TransformationError::ConfigError {
            message: format!("Failed to read config file: {}", e),
        })?;

        let config: Self =
            toml::from_str(&content).map_err(|e| TransformationError::ConfigError {
                message: format!("Failed to parse config file: {}", e),
            })?;

        config.validate()?;
        Ok(config)
    }

    pub fn from_env() -> Self {
        let mut config = Self::default();

        if let Ok(val) = std::env::var("PGT_PRESERVE_PRECISION") {
            config.data_types.preserve_precision = val.parse().unwrap_or(true);
        }

        if let Ok(val) = std::env::var("PGT_PRESERVE_CASE") {
            config.functions.preserve_case = val.parse().unwrap_or(false);
        }

        if let Ok(val) = std::env::var("PGT_STRICT_MODE") {
            config.rules.enable_strict_mode = val.parse().unwrap_or(false);
        }

        if let Ok(val) = std::env::var("PGT_VALIDATE_COMPATIBILITY") {
            config.rules.validate_hana_compatibility = val.parse().unwrap_or(true);
        }

        config
    }

    pub fn merge(configs: Vec<Self>) -> TransformationResult<Self> {
        let mut result = Self::default();

        for config in configs {
            result.data_types.preserve_precision = config.data_types.preserve_precision;
            result.data_types.handle_arrays = config.data_types.handle_arrays;
            result
                .data_types
                .custom_mappings
                .extend(config.data_types.custom_mappings);

            result.functions.preserve_case = config.functions.preserve_case;
            result
                .functions
                .custom_mappings
                .extend(config.functions.custom_mappings);

            result.schema_handling = config.schema_handling;
            result.optimization = config.optimization;
            result.formatting = config.formatting;

            result.rules.enable_strict_mode = config.rules.enable_strict_mode;
            result.rules.validate_hana_compatibility = config.rules.validate_hana_compatibility;
            result
                .rules
                .transformation_rules
                .extend(config.rules.transformation_rules);
        }

        result.validate()?;
        Ok(result)
    }

    pub fn validate(&self) -> TransformationResult<()> {
        let mut errors = Vec::new();

        for (key, value) in &self.data_types.custom_mappings {
            if key.is_empty() {
                errors.push("Data type mapping cannot have empty key".to_string());
            }
            if value.is_empty() {
                errors.push(format!(
                    "Data type mapping for '{}' cannot have empty value",
                    key
                ));
            }
        }

        for (key, value) in &self.functions.custom_mappings {
            if key.is_empty() {
                errors.push("Function mapping cannot have empty key".to_string());
            }
            if value.is_empty() {
                errors.push(format!(
                    "Function mapping for '{}' cannot have empty value",
                    key
                ));
            }
        }

        if errors.is_empty() {
            Ok(())
        } else {
            Err(TransformationError::ConfigError {
                message: errors.join("; "),
            })
        }
    }

    pub fn apply_defaults(&mut self) {
        if self.data_types.custom_mappings.is_empty() {
            self.data_types.custom_mappings = Self::get_default_data_type_mappings();
        }

        if self.functions.custom_mappings.is_empty() {
            self.functions.custom_mappings = Self::get_default_function_mappings();
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RulesConfig {
    pub enable_strict_mode: bool,
    pub validate_hana_compatibility: bool,
    pub transformation_rules: HashMap<String, bool>,
}

impl Default for RulesConfig {
    fn default() -> Self {
        Self {
            enable_strict_mode: false,
            validate_hana_compatibility: true,
            transformation_rules: HashMap::new(),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use pretty_assertions::assert_eq;

    // Helper: generate a valid TOML string by serializing the default config.
    // This ensures the TOML always has all required fields (including custom_mappings tables).
    fn full_toml() -> String {
        let c = TransformationConfig::default();
        toml::to_string_pretty(&c).expect("default config should serialize to TOML")
    }

    // --- TransformationConfig::default ---

    #[test]
    fn default_has_all_subconfigs() {
        let c = TransformationConfig::default();
        // access each subconfig field to verify they exist
        let _ = c.data_types;
        let _ = c.functions;
        let _ = c.schema_handling;
        let _ = c.optimization;
        let _ = c.formatting;
        let _ = c.rules;
    }

    #[test]
    fn default_data_types_preserve_precision_is_true() {
        let c = TransformationConfig::default();
        assert!(c.data_types.preserve_precision);
    }

    #[test]
    fn default_functions_preserve_case_is_false() {
        let c = TransformationConfig::default();
        assert!(!c.functions.preserve_case);
    }

    #[test]
    fn default_schema_handling_default_schema_is_public() {
        let c = TransformationConfig::default();
        assert_eq!(c.schema_handling.default_schema, "PUBLIC");
    }

    // --- TransformationConfig::to_file / from_file ---

    #[test]
    fn to_file_then_from_file_round_trips() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("c.toml");
        let original = TransformationConfig::default();
        original.to_file(&path).unwrap();
        let parsed = TransformationConfig::from_file(&path).unwrap();
        assert_eq!(
            parsed.data_types.preserve_precision,
            original.data_types.preserve_precision
        );
        assert_eq!(
            parsed.functions.preserve_case,
            original.functions.preserve_case
        );
        assert_eq!(
            parsed.schema_handling.default_schema,
            original.schema_handling.default_schema
        );
    }

    #[test]
    fn from_file_parses_valid_toml() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("c.toml");
        std::fs::write(&path, full_toml()).unwrap();
        let c = TransformationConfig::from_file(&path).unwrap();
        assert!(c.data_types.preserve_precision);
    }

    #[test]
    fn from_file_missing_file_errors() {
        let result = TransformationConfig::from_file("/nonexistent/path/missing.toml");
        assert!(result.is_err());
    }

    #[test]
    fn from_file_invalid_toml_errors() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("bad.toml");
        std::fs::write(&path, "not valid toml {{ }}").unwrap();
        let result = TransformationConfig::from_file(&path);
        assert!(result.is_err());
    }

    // --- TransformationConfig::from_env ---

    #[test]
    fn from_env_reads_preserve_precision_false() {
        std::env::set_var("PGT_PRESERVE_PRECISION", "false");
        let c = TransformationConfig::from_env();
        std::env::remove_var("PGT_PRESERVE_PRECISION");
        assert!(!c.data_types.preserve_precision);
    }

    #[test]
    fn from_env_reads_preserve_case_true() {
        std::env::set_var("PGT_PRESERVE_CASE", "true");
        let c = TransformationConfig::from_env();
        std::env::remove_var("PGT_PRESERVE_CASE");
        assert!(c.functions.preserve_case);
    }

    #[test]
    fn from_env_reads_strict_mode() {
        std::env::set_var("PGT_STRICT_MODE", "true");
        let c = TransformationConfig::from_env();
        std::env::remove_var("PGT_STRICT_MODE");
        assert!(c.rules.enable_strict_mode);
    }

    #[test]
    fn from_env_reads_validate_compatibility_false() {
        std::env::set_var("PGT_VALIDATE_COMPATIBILITY", "false");
        let c = TransformationConfig::from_env();
        std::env::remove_var("PGT_VALIDATE_COMPATIBILITY");
        assert!(!c.rules.validate_hana_compatibility);
    }

    #[test]
    fn from_env_no_vars_never_panics() {
        // Remove all known env vars to test default behavior
        std::env::remove_var("PGT_PRESERVE_PRECISION");
        std::env::remove_var("PGT_PRESERVE_CASE");
        std::env::remove_var("PGT_STRICT_MODE");
        std::env::remove_var("PGT_VALIDATE_COMPATIBILITY");
        let c = TransformationConfig::from_env();
        c.validate().unwrap();
    }

    // --- TransformationConfig::merge ---

    #[test]
    fn merge_combines_non_default_fields() {
        let a = TransformationConfig::default();
        let b = TransformationConfig::default();
        let merged = TransformationConfig::merge(vec![a, b]).unwrap();
        merged.validate().unwrap();
    }

    #[test]
    fn merge_empty_vec_produces_default() {
        let merged = TransformationConfig::merge(vec![]).unwrap();
        merged.validate().unwrap();
    }

    #[test]
    fn merge_last_wins_for_schema() {
        let mut a = TransformationConfig::default();
        a.schema_handling.default_schema = "SCHEMA_A".to_string();
        let mut b = TransformationConfig::default();
        b.schema_handling.default_schema = "SCHEMA_B".to_string();
        let merged = TransformationConfig::merge(vec![a, b]).unwrap();
        assert_eq!(merged.schema_handling.default_schema, "SCHEMA_B");
    }

    #[test]
    fn merge_extends_custom_data_type_mappings() {
        let mut a = TransformationConfig::default();
        a.data_types.custom_mappings.insert("FOO".to_string(), "BAR".to_string());
        let mut b = TransformationConfig::default();
        b.data_types.custom_mappings.insert("BAZ".to_string(), "QUX".to_string());
        let merged = TransformationConfig::merge(vec![a, b]).unwrap();
        assert!(merged.data_types.custom_mappings.contains_key("FOO"));
        assert!(merged.data_types.custom_mappings.contains_key("BAZ"));
    }

    // --- TransformationConfig::validate ---

    #[test]
    fn validate_accepts_default() {
        TransformationConfig::default().validate().unwrap();
    }

    #[test]
    fn validate_rejects_empty_key_in_data_type_mappings() {
        let mut c = TransformationConfig::default();
        c.data_types.custom_mappings.insert("".to_string(), "NVARCHAR".to_string());
        assert!(c.validate().is_err());
    }

    #[test]
    fn validate_rejects_empty_value_in_data_type_mappings() {
        let mut c = TransformationConfig::default();
        c.data_types.custom_mappings.insert("TEXT".to_string(), "".to_string());
        assert!(c.validate().is_err());
    }

    #[test]
    fn validate_rejects_empty_key_in_function_mappings() {
        let mut c = TransformationConfig::default();
        c.functions.custom_mappings.insert("".to_string(), "RAND".to_string());
        assert!(c.validate().is_err());
    }

    #[test]
    fn validate_rejects_empty_value_in_function_mappings() {
        let mut c = TransformationConfig::default();
        c.functions.custom_mappings.insert("NOW".to_string(), "".to_string());
        assert!(c.validate().is_err());
    }

    // --- TransformationConfig::apply_defaults ---

    #[test]
    fn apply_defaults_populates_missing_mappings() {
        let mut c = TransformationConfig::default();
        c.apply_defaults();
        c.validate().unwrap();
        // apply_defaults fills custom_mappings when empty
        assert!(!c.data_types.custom_mappings.is_empty());
        assert!(!c.functions.custom_mappings.is_empty());
    }

    #[test]
    fn apply_defaults_does_not_overwrite_existing_mappings() {
        let mut c = TransformationConfig::default();
        c.data_types.custom_mappings.insert("MYTYPE".to_string(), "NVARCHAR".to_string());
        c.apply_defaults();
        // Existing mappings are preserved (apply_defaults only fills when empty)
        assert!(c.data_types.custom_mappings.contains_key("MYTYPE"));
    }

    // --- TransformationConfig::get_default_data_type_mappings ---

    #[test]
    fn default_data_type_mappings_includes_serial() {
        let m = TransformationConfig::get_default_data_type_mappings();
        assert!(m.contains_key("SERIAL"), "missing SERIAL mapping: {:?}", m.keys());
    }

    #[test]
    fn default_data_type_mappings_includes_bigserial() {
        let m = TransformationConfig::get_default_data_type_mappings();
        assert!(m.contains_key("BIGSERIAL"));
    }

    #[test]
    fn default_data_type_mappings_includes_text() {
        let m = TransformationConfig::get_default_data_type_mappings();
        assert!(m.contains_key("TEXT"));
    }

    #[test]
    fn default_data_type_mappings_non_empty() {
        let m = TransformationConfig::get_default_data_type_mappings();
        assert!(!m.is_empty());
    }

    // --- TransformationConfig::get_default_function_mappings ---

    #[test]
    fn default_function_mappings_includes_random() {
        // Per source: RANDOM → RAND (NOW is NOT in the map - it's natively supported)
        let m = TransformationConfig::get_default_function_mappings();
        assert!(
            m.contains_key("RANDOM") || m.contains_key("random"),
            "missing RANDOM mapping: {:?}", m.keys()
        );
    }

    #[test]
    fn default_function_mappings_non_empty() {
        let m = TransformationConfig::get_default_function_mappings();
        assert!(!m.is_empty());
    }

    // --- DataTypeConfig shape ---

    #[test]
    fn data_type_config_fields_accessible() {
        let c = DataTypeConfig::default();
        let _ = c.preserve_precision;
        let _ = c.custom_mappings;
        let _ = c.handle_arrays;
    }

    // --- ArrayHandlingStrategy shape ---

    #[test]
    fn array_handling_strategy_variants_are_clone_debug() {
        let variants = [
            ArrayHandlingStrategy::AsJson,
            ArrayHandlingStrategy::AsDelimitedString,
            ArrayHandlingStrategy::AsMultipleColumns,
            ArrayHandlingStrategy::Error,
        ];
        for v in &variants {
            let cloned = v.clone();
            let _ = format!("{:?}", cloned);
        }
    }

    // --- FunctionConfig shape ---

    #[test]
    fn function_config_fields_accessible() {
        let c = FunctionConfig::default();
        let _ = c.preserve_case;
        let _ = c.enable_custom_functions;
        let _ = c.custom_mappings;
    }

    // --- SchemaConfig shape ---

    #[test]
    fn schema_config_fields_accessible() {
        let c = SchemaConfig::default();
        let _ = c.default_schema;
        let _ = c.preserve_schema_names;
        let _ = c.schema_mappings;
    }

    // --- OptimizationConfig shape ---

    #[test]
    fn optimization_config_fields_accessible() {
        let c = OptimizationConfig::default();
        let _ = c.use_column_store_hints;
        let _ = c.enable_parallel_execution;
        let _ = c.suggest_indexes;
    }

    // --- FormattingConfig shape ---

    #[test]
    fn formatting_config_fields_accessible() {
        let c = FormattingConfig::default();
        let _ = c.indent_size;
        let _ = c.max_line_length;
        let _ = c.capitalize_keywords;
        let _ = c.preserve_comments;
    }

    // --- RulesConfig shape ---

    #[test]
    fn rules_config_fields_accessible() {
        let c = RulesConfig::default();
        let _ = c.enable_strict_mode;
        let _ = c.validate_hana_compatibility;
        let _ = c.transformation_rules;
    }

    #[test]
    fn rules_config_default_values() {
        let c = RulesConfig::default();
        assert!(!c.enable_strict_mode);
        assert!(c.validate_hana_compatibility);
        assert!(c.transformation_rules.is_empty());
    }
}
