// Pure tests for the swagger 2.0 generator (Response/OpenAPI.hs port):
// structure of paths/definitions/parameters/securityDefinitions, the
// host/basePath handling from openapi-server-proxy-uri, and the OPTIONS
// Allow-header builders (Response.hs info*Response).

import { assertEquals, assertStringIncludes, assertThrows } from "std/assert/mod.ts";
import { type AppConfig, resolveConfig } from "../functions/config.ts";
import { PgrstError } from "../functions/errors.ts";
import {
  docsVersion,
  encodeOpenApi,
  escapeHostName,
  parseDefault,
  pickProxy,
  prettyVersion,
  proxyUri,
  toSwaggerType,
} from "../functions/openapi.ts";
import { infoIdentResponse, infoProcResponse, infoRootResponse } from "../functions/response.ts";
import type {
  Column,
  Relationship,
  RelationshipsMap,
  Routine,
  SchemaCache,
  Table,
} from "../functions/schema-cache/types.ts";
import { relsMapKey } from "../functions/schema-cache/types.ts";

// --------------------------------------------------------------------------
// Fixtures
// --------------------------------------------------------------------------

function conf(env: Record<string, string> = {}): AppConfig {
  return resolveConfig({ env: { PGRST_DB_SCHEMAS: "test", ...env } });
}

const qi = (name: string) => ({ schema: "test", name });

function col(name: string, dataType: string, extra: Partial<Column> = {}): Column {
  return {
    name,
    description: null,
    nullable: true,
    dataType,
    nominalType: dataType,
    maxLen: null,
    default: null,
    enumVals: [],
    ...extra,
  };
}

const projects: Table = {
  schema: "test",
  name: "projects",
  description: "All projects\n\nSecond line of description",
  kind: "table",
  insertable: true,
  updatable: true,
  deletable: true,
  pkCols: ["id"],
  columns: [
    col("id", "integer", { nullable: false, description: "the id" }),
    col("name", "character varying", { maxLen: 64, default: "'anon'::character varying" }),
    col("client_id", "integer"),
    col("tags", "text[]"),
    col("status", "text", { enumVals: ["open", "closed"] }),
    col("data", "jsonb"),
  ],
};

// a non-writable relation only exposes GET
const stats: Table = {
  schema: "test",
  name: "stats",
  description: null,
  kind: "view",
  insertable: false,
  updatable: false,
  deletable: false,
  pkCols: [],
  columns: [col("total", "bigint")],
};

const projectsClientsM2O: Relationship = {
  kind: "fk",
  table: qi("projects"),
  foreignTable: qi("clients"),
  isSelf: false,
  cardinality: { tag: "M2O", constraint: "projects_client_id_fkey", columns: [["client_id", "id"]] },
  tableIsView: false,
  foreignTableIsView: false,
};

const rels: RelationshipsMap = new Map([[relsMapKey(qi("projects"), "test"), [projectsClientsM2O]]]);

const addThem: Routine = {
  schema: "test",
  name: "add_them",
  description: "adds them\ndetails here",
  params: [
    { name: "a", type: "integer", typeMaxLength: "integer", required: true, variadic: false },
    { name: "b", type: "integer", typeMaxLength: "integer", required: false, variadic: false },
    { name: "v", type: "text[]", typeMaxLength: "text[]", required: false, variadic: true },
  ],
  returnType: { kind: "single", pgType: { qi: { schema: "pg_catalog", name: "int4" }, composite: false, compositeAlias: false } },
  volatility: "immutable",
  hasVariadic: true,
  isolationLvl: null,
  funcSettings: [],
};

function spec(env: Record<string, string> = {}, sd: string | null = "My API\nlonger description"): Record<string, unknown> {
  return JSON.parse(encodeOpenApi(conf(env), rels, [projects, stats], [addThem], sd));
}

// --------------------------------------------------------------------------
// Top-level structure
// --------------------------------------------------------------------------

Deno.test("openapi: top-level swagger fields, info from the schema comment", () => {
  const doc = spec();
  assertEquals(doc.swagger, "2.0");
  assertEquals(doc.basePath, "/");
  assertEquals(doc.schemes, ["http"]);
  assertEquals(doc.host, "0.0.0.0:3000"); // server-host default "!4" escapes
  assertEquals(doc.info, { description: "longer description", title: "My API", version: prettyVersion });
  assertEquals(doc.externalDocs, {
    description: "PostgREST Documentation",
    url: `https://postgrest.org/en/${docsVersion}/references/api.html`,
  });
  assertEquals(doc.produces, doc.consumes);
  assertEquals((doc.produces as string[])[0], "application/json");
  // no security definitions unless openapi-security-active
  assertEquals("securityDefinitions" in doc, false);
  assertEquals("security" in doc, false);
});

Deno.test("openapi: defaults for title/description when there is no schema comment", () => {
  const doc = spec({}, null);
  assertEquals(doc.info, {
    description: "This is a dynamic API generated by PostgREST",
    title: "PostgREST API",
    version: prettyVersion,
  });
});

Deno.test("openapi: single-line schema comment yields an EMPTY info.description", () => {
  // OpenAPI.hs: breakOn "\n" gives (title, Just "") — so the "dynamic API"
  // fallback does NOT apply (MultipleSchemaSpec "builds openapi for a valid
  // schema": COMMENT ON SCHEMA v1 IS 'v1 schema' -> description "").
  const doc = spec({}, "v1 schema");
  assertEquals(doc.info, { description: "", title: "v1 schema", version: prettyVersion });
  // ...while path items filter the empty description out (mfilter (/=""))
  const single = JSON.parse(
    encodeOpenApi(conf(), rels, [{ ...projects, description: "one liner" }], [], "v1 schema"),
  );
  const getOp = (single.paths as Record<string, Record<string, Record<string, unknown>>>)["/projects"].get;
  assertEquals(getOp.summary, "one liner");
  assertEquals("description" in getOp, false);
});

Deno.test("openapi: an empty schema omits the definitions key entirely", () => {
  // swagger2's ToJSON omits mempty maps; the oracle's nonexistent-schema
  // OpenAPI output has no "definitions" key at all (ErrorSpec.nonExistentSchema).
  const doc = JSON.parse(encodeOpenApi(conf(), new Map(), [], [], null));
  assertEquals("definitions" in doc, false);
  assertEquals(Object.keys(doc.paths as Record<string, unknown>), ["/"]);
});

Deno.test("openapi: proxy uri drives scheme/host/port/basePath", () => {
  const doc = spec({ PGRST_OPENAPI_SERVER_PROXY_URI: "https://postgrest.com:8443/openapi" });
  assertEquals(doc.schemes, ["https"]);
  assertEquals(doc.host, "postgrest.com:8443");
  assertEquals(doc.basePath, "/openapi");
  // default ports per scheme
  assertEquals(proxyUri(conf({ PGRST_OPENAPI_SERVER_PROXY_URI: "https://example.com/base" })), [
    "https",
    "example.com",
    443,
    "/base",
  ]);
  // malformed proxy uris fall back to server-host/server-port
  assertEquals(pickProxy("ftp://example.com"), null);
  assertEquals(pickProxy("http://user:pw@example.com"), null);
  assertEquals(pickProxy("http://example.com/?query=1"), null);
  assertEquals(pickProxy("not a uri"), null);
  const fallback = spec({ PGRST_OPENAPI_SERVER_PROXY_URI: "ftp://example.com", PGRST_SERVER_HOST: "myhost", PGRST_SERVER_PORT: "4000" });
  assertEquals(fallback.host, "myhost:4000");
});

Deno.test("openapi: security definitions under openapi-security-active", () => {
  const doc = spec({ PGRST_OPENAPI_SECURITY_ACTIVE: "true" });
  assertEquals(doc.securityDefinitions, {
    JWT: {
      type: "apiKey",
      description: 'Add the token prepending "Bearer " (without quotes) to it',
      name: "Authorization",
      in: "header",
    },
  });
  assertEquals(doc.security, [{ JWT: [] }]);
});

// --------------------------------------------------------------------------
// Definitions
// --------------------------------------------------------------------------

Deno.test("openapi: table definitions carry typed properties, PK/FK notes, enums and defaults", () => {
  const doc = spec();
  const defs = doc.definitions as Record<string, Record<string, unknown>>;
  const def = defs.projects;
  assertEquals(def.type, "object");
  assertEquals(def.description, "All projects\n\nSecond line of description");
  assertEquals(def.required, ["id"]); // not-null columns
  const props = def.properties as Record<string, Record<string, unknown>>;
  assertEquals(props.id, {
    description: "the id\n\nNote:\nThis is a Primary Key.<pk/>",
    format: "integer",
    type: "integer",
  });
  assertEquals(props.client_id.description, [
    "Note:",
    "This is a Foreign Key to `clients.id`.<fk table='clients' column='id'/>",
  ].join("\n"));
  assertEquals(props.name, { default: "anon", format: "character varying", maxLength: 64, type: "string" });
  assertEquals(props.tags, { format: "text[]", type: "array", items: { type: "string" } });
  assertEquals(props.status, { enum: ["open", "closed"], format: "text", type: "string" });
  // json/jsonb have a format but no swagger type
  assertEquals(props.data, { format: "jsonb" });
  // the view definition has no required entries
  assertEquals("required" in defs.stats, false);
});

Deno.test("openapi: toSwaggerType/parseDefault corner cases", () => {
  assertEquals(toSwaggerType("double precision"), "number");
  assertEquals(toSwaggerType("integer[]"), "array");
  assertEquals(toSwaggerType("tsrange"), "string");
  assertEquals(toSwaggerType("jsonb"), undefined);
  assertEquals(parseDefault("text", "'hi'::text"), '"hi"');
  assertEquals(parseDefault("integer", "42"), "42");
});

// --------------------------------------------------------------------------
// Parameters + paths
// --------------------------------------------------------------------------

Deno.test("openapi: reserved parameters, per-column rowFilters and body params", () => {
  const doc = spec();
  const params = doc.parameters as Record<string, Record<string, unknown>>;
  for (const name of ["preferParams", "preferReturn", "preferCount", "preferPost", "select", "on_conflict", "order", "range", "rangeUnit", "offset", "limit"]) {
    assertEquals(name in params, true, `missing parameter def ${name}`);
  }
  assertEquals(params.preferReturn.enum, ["return=representation", "return=minimal", "return=none"]);
  assertEquals(params.rangeUnit.default, "items");
  assertEquals(params.select, { name: "select", description: "Filtering Columns", required: false, in: "query", type: "string" });
  assertEquals(params["rowFilter.projects.id"], { name: "id", description: "the id", required: false, in: "query", type: "string" });
  assertEquals(params["body.projects"], {
    name: "projects",
    description: "projects",
    required: false,
    in: "body",
    schema: { $ref: "#/definitions/projects" },
  });
});

Deno.test("openapi: table paths — writable tables get all verbs, read-only just GET", () => {
  const doc = spec();
  const paths = doc.paths as Record<string, Record<string, Record<string, unknown>>>;
  assertEquals(Object.keys(paths), ["/", "/projects", "/stats", "/rpc/add_them"]);
  assertEquals(Object.keys(paths["/projects"]), ["get", "post", "patch", "delete"]);
  assertEquals(Object.keys(paths["/stats"]), ["get"]);
  const getOp = paths["/projects"].get;
  assertEquals(getOp.tags, ["projects"]);
  assertEquals(getOp.summary, "All projects");
  assertEquals(getOp.description, "Second line of description");
  assertEquals(getOp.responses, {
    "200": { description: "OK", schema: { items: { $ref: "#/definitions/projects" }, type: "array" } },
    "206": { description: "Partial Content" },
  });
  const getParams = getOp.parameters as { $ref: string }[];
  assertEquals(getParams[0], { $ref: "#/parameters/rowFilter.projects.id" });
  assertEquals(getParams[getParams.length - 1], { $ref: "#/parameters/preferCount" });
  assertEquals((paths["/projects"].post.parameters as unknown[])[0], { $ref: "#/parameters/body.projects" });
  assertEquals(paths["/projects"].post.responses, { "201": { description: "Created" } });
  assertEquals(paths["/projects"].delete.responses, { "204": { description: "No Content" } });
  // root path item
  assertEquals(paths["/"].get.summary, "OpenAPI description (this document)");
  assertEquals(paths["/"].get.produces, ["application/openapi+json", "application/json"]);
});

Deno.test("openapi: rpc paths — GET query params (incl. variadic) and POST args body", () => {
  const doc = spec();
  const paths = doc.paths as Record<string, Record<string, Record<string, unknown>>>;
  const rpc = paths["/rpc/add_them"];
  assertEquals(Object.keys(rpc), ["get", "post"]);
  assertEquals(rpc.get.tags, ["(rpc) add_them"]);
  assertEquals(rpc.get.summary, "adds them");
  assertEquals(rpc.get.description, "details here");
  assertEquals(rpc.get.produces, [
    "application/json",
    "application/vnd.pgrst.object+json;nulls=stripped",
    "application/vnd.pgrst.object+json",
  ]);
  const getParams = rpc.get.parameters as Record<string, unknown>[];
  assertEquals(getParams[0], { name: "a", required: true, in: "query", format: "integer", type: "integer" });
  assertEquals(getParams[2], {
    name: "v",
    required: false,
    in: "query",
    type: "array",
    items: { format: "text", type: "string" },
    collectionFormat: "multi",
  });
  const postParams = rpc.post.parameters as Record<string, unknown>[];
  assertEquals(postParams[1], { $ref: "#/parameters/preferParams" });
  const args = postParams[0] as { schema: Record<string, unknown> };
  assertEquals(args.schema.type, "object");
  assertEquals(args.schema.required, ["a"]);
  assertEquals((args.schema.properties as Record<string, unknown>).a, { format: "integer", type: "integer" });
});

Deno.test("openapi: empty properties/parameters are omitted (swagger2 omits mempty fields)", () => {
  // swagger2's sopSwaggerGenericToJSON drops fields equal to their mempty
  // default: a column-less relation has NO "properties" key and a paramless
  // routine's GET operation has NO "parameters" key.
  const bare: Table = { ...stats, name: "bare", columns: [] };
  const noArgs: Routine = { ...addThem, name: "no_args", description: null, params: [] };
  const doc = JSON.parse(encodeOpenApi(conf(), rels, [bare], [noArgs], null));
  const defs = doc.definitions as Record<string, Record<string, unknown>>;
  assertEquals("properties" in defs.bare, false);
  assertEquals(defs.bare.type, "object");
  const rpc = (doc.paths as Record<string, Record<string, Record<string, unknown>>>)["/rpc/no_args"];
  assertEquals("parameters" in rpc.get, false);
  // POST still carries the args body + preferParams, with an empty schema
  const postParams = rpc.post.parameters as { schema?: Record<string, unknown> }[];
  assertEquals(postParams.length, 2);
  assertEquals("properties" in (postParams[0].schema as Record<string, unknown>), false);
});

// --------------------------------------------------------------------------
// OPTIONS Allow headers (Response.hs info*Response)
// --------------------------------------------------------------------------

const infoCache: SchemaCache = {
  tables: new Map([
    ["test.projects", projects],
    ["test.stats", stats],
    ["test.nopk", { ...projects, name: "nopk", pkCols: [] }],
    ["test.insert_only", { ...projects, name: "insert_only", updatable: false, deletable: false }],
  ]),
  relationships: new Map(),
  routines: new Map(),
  representations: new Map(),
  mediaHandlers: [],
  timezones: new Set(),
};

Deno.test("OPTIONS: per-table Allow follows insertable/updatable/deletable and the PK for PUT", () => {
  const allow = (name: string) => infoIdentResponse(qi(name), infoCache).headers.get("Allow");
  assertEquals(allow("projects"), "OPTIONS,GET,HEAD,POST,PUT,PATCH,DELETE");
  assertEquals(allow("stats"), "OPTIONS,GET,HEAD");
  // no PK → no PUT
  assertEquals(allow("nopk"), "OPTIONS,GET,HEAD,POST,PATCH,DELETE");
  // insertable but not updatable → no PUT/PATCH
  assertEquals(allow("insert_only"), "OPTIONS,GET,HEAD,POST");
  const res = infoIdentResponse(qi("projects"), infoCache);
  assertEquals(res.status, 200);
  assertEquals(res.headers.get("Access-Control-Allow-Origin"), "*");
  // unknown table → 404
  const err = assertThrows(() => infoIdentResponse(qi("missing"), infoCache)) as PgrstError;
  assertEquals(err.status, 404);
});

Deno.test("OPTIONS: routines allow POST always, GET/HEAD only when not volatile; root is read-only", () => {
  assertEquals(infoProcResponse(addThem).headers.get("Allow"), "OPTIONS,GET,HEAD,POST");
  assertEquals(infoProcResponse({ ...addThem, volatility: "volatile" }).headers.get("Allow"), "OPTIONS,POST");
  assertEquals(infoRootResponse().headers.get("Allow"), "OPTIONS,GET,HEAD");
});

Deno.test("openapi: escapeHostName maps the wildcard listen addresses", () => {
  for (const h of ["*", "*4", "!4", "*6", "!6"]) assertEquals(escapeHostName(h), "0.0.0.0");
  assertEquals(escapeHostName("example.com"), "example.com");
});

Deno.test("openapi: the encoded document is valid JSON with stable key spelling", () => {
  const text = encodeOpenApi(conf(), rels, [projects], [addThem], null);
  assertStringIncludes(text, '"swagger":"2.0"');
  assertStringIncludes(text, '"rowFilter.projects.id"');
});
